## 
## With the functions makeCacheMatrix and cacheSolve one can 
## calculate the inverse of a square matrix.
## The method will cache the inverse of the matrix so these 
## methods are only usefull if the inverse of a matrix is 
## used more than one time.
##
## Note: The methods work only for matrixes which are invertable!
##  Example
##  a <- matrix(c(-2,-2,6,-2,-1,-1,9,0,5,-3,-1,0,-10,3,-1,0), nrow=4, ncol=4, byrow=TRUE)
##
##  solve(a) returns
##      [,1]        [,2]        [,3]        [,4]
## [1,]  0.0 -0.03846154 -0.16666667 -0.17948718
## [2,]  0.0 -0.09615385 -0.58333333 -0.28205128
## [3,]  0.0  0.09615385 -0.08333333 -0.05128205
## [4,] -0.5  0.42307692  0.50000000  0.30769231
##
## we can expect to get the same result with this method:
## b <- makeCacheMatrix(a)
## 
## 
## cacheSolve(b)
##      [,1]        [,2]        [,3]        [,4]
## [1,]  0.0 -0.03846154 -0.16666667 -0.17948718
## [2,]  0.0 -0.09615385 -0.58333333 -0.28205128
## [3,]  0.0  0.09615385 -0.08333333 -0.05128205
## [4,] -0.5  0.42307692  0.50000000  0.30769231
##
## 
## second call to will return the same result + the hint that a cached 
## result is returned
## cacheSolve(b)
## getting cached data
##      [,1]        [,2]        [,3]        [,4]
## [1,]  0.0 -0.03846154 -0.16666667 -0.17948718
## [2,]  0.0 -0.09615385 -0.58333333 -0.28205128
## [3,]  0.0  0.09615385 -0.08333333 -0.05128205
## [4,] -0.5  0.42307692  0.50000000  0.30769231




## makeCacheMatrix takes a (square) matrix and stores it internally.
## It offers to store the inverse matrix together with the original matrix
## The following methods are offered by the resulting 'object' returned
## - get: get the original matrix
## - set: set a new matrix
## - setinv: store the inverted matrix in the 'object'
## - getinv: get the inverted matrix. If no inverted matrix was stored before 'Null' is returned
makeCacheMatrix <- function(x = matrix()) {
  ## clean the variable which will contain the inverted matrix once it is calculated
  cachedValue <- NULL
  
  ## setter method for the matrix
  set <- function(y) {
    x <<- y
    ## clean an result of a previous calculation when a new value is set
    cachedValue <<- NULL
  }
  
  ## getter method for the matrix
  get <- function() x
  
  ## setter for the inverted matrix
  setinv <- function(inv) cachedValue <<- inv
  
  ## getter for the inverted matrix
  getinv <- function() cachedValue
  
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


## The cachsolve function takes as input a 'cachable matrix' generated by makeCacheMatrix.
## First the method checks if in the input object a inverted matrix is stored.
## If yes this result is returned and the function returns this result
## If not the original data is retrieved from x and the inverted matrix is calculated by calling solve.
## This result is stored in the object x by calling setinv. Finally the inverted matrix is returned.
## 
cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  
  ## get cached data
  m <- x$getinv()
  ## if not null we have cached data found
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  
  ## no chached data - calculate and store
  data <- x$get()
  m <- solve(data, ...)
  x$setinv(m)
  return (m)
}
